import fs from 'node:fs';
import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
const root='/Users/marwan/Documents/Golderapharm';
const require=createRequire(`${root}/goldBack/package.json`);
require('dotenv').config({path:`${root}/goldBack/.env`,quiet:true});
const state=JSON.parse(fs.readFileSync('/private/tmp/goldera-full-qa.json','utf8'));
if (!/^goldera_qa_20261004_[a-f0-9]{10}$/.test(state.schema) || new URL(state.databaseUrl).searchParams.get("schema") !== state.schema) throw new Error("Refusing to run outside the disposable QA schema");
process.env.DATABASE_URL=state.databaseUrl;
const {prisma}=await import(`${root}/goldBack/config/db.js`);
const f=state.fixtures,tokens={},results=[];
async function api(role,method,path,body) {
  const form=body instanceof FormData;
  const response=await fetch(`http://localhost:5051/api${path}`,{method,headers:{...(form?{}:{'Content-Type':'application/json'}),...(tokens[role]?{Authorization:`Bearer ${tokens[role]}`}:{})},...(body===undefined?{}:{body:form?body:JSON.stringify(body)}),signal:AbortSignal.timeout(45000)});
  return {status:response.status,data:await response.json()};
}
const status=(r,expected)=>assert.ok(expected.includes(r.status),`Expected ${expected.join('/')} got ${r.status}: ${r.data.message}`);
async function test(name,fn){try{await fn();results.push({name,pass:true});}catch(e){results.push({name,pass:false,evidence:e.message});}}
for(const role of ['manager','outsider','supervisor','rep','rep2']){const r=await api(null,'POST','/auth/login',{email:f[role].email,password:state.password});status(r,[200]);tokens[role]=r.data.token;}
await test('Notifications require authentication',async()=>status(await api(null,'GET','/notifications'),[401]));
await test('Rep notification feed contains actual decisions',async()=>{const r=await api('rep','GET','/notifications');status(r,[200]);assert.equal(r.data.userId,f.rep.id);assert.ok(r.data.data.some(n=>n.title.includes('approved')));assert.ok(r.data.data.every(n=>n.href.startsWith('/rep/')));});
await test('Manager notification feed contains team pending requests',async()=>{const r=await api('manager','GET','/notifications');status(r,[200]);assert.equal(r.data.userId,f.manager.id);assert.ok(r.data.data.every(n=>n.href.startsWith('/manager/')));});
await test('Team includes assigned territory',async()=>{const r=await api('manager','GET','/managers/team');status(r,[200]);const rep=r.data.data.find(u=>u.id===f.rep.id);assert.equal(rep.subRegion.id,f.subRegion.id);assert.equal(rep.subRegion.region.id,f.region.id);});
await test('Manager cannot modify outside team member',async()=>status(await api('manager','PUT',`/managers/users/${f.rep2.id}`,{name:'Unauthorized'}),[403]));
await test('Manager cannot delete self',async()=>status(await api('manager','DELETE',`/managers/users/${f.manager.id}`),[400]));
await test('Manager cannot disable self',async()=>status(await api('manager','PUT',`/managers/users/${f.manager.id}`,{isActive:false}),[400]));
await test('Profile cannot change leave balance',async()=>status(await api('rep','PATCH','/profiles',{leaveDaysCountTotal:500}),[400]));
await test('Manager cannot write arbitrary member ID',async()=>status(await api('manager','PUT',`/managers/users/${f.rep.id}`,{id:'arbitrary'}),[400]));
await test('Manager role filter works for visits and team screens',async()=>{for(const role of ['MEDICAL_REP','SUPERVISOR']){const r=await api('manager','GET',`/managers/team?role=${role}&limit=1000`);status(r,[200]);assert.ok(r.data.data.length);assert.ok(r.data.data.every(u=>u.role===role));}});
await test('Supervisor dashboard endpoint serves scoped data',async()=>{const r=await api('supervisor','GET','/dashboard/supervisors');status(r,[200]);assert.ok(r.data.data.requests.every(v=>v.userId!==f.rep2.id));});
await test('Supervisor sales endpoint serves assigned territories',async()=>{const r=await api('supervisor','GET','/sales');status(r,[200]);assert.ok(r.data.data.every(v=>v.customer==='QA Pharmacy'));});
await test('Sales rep selector cannot expose another manager team',async()=>{for(const actor of ['manager','supervisor'])status(await api(actor,'GET',`/sales/reps/${f.rep2.id}`),[403]);});
await test('Unassigned rep does not inherit all company sales',async()=>{const r=await api('rep2','GET','/sales/reps');status(r,[200]);assert.equal(r.data.results,0);});
await test('Bulk doctor import rejects empty names atomically',async()=>{const before=await prisma.doctor.count();status(await api('manager','POST','/doctors/bulk-import',{records:[{nameEN:'QA Good Row'},{nameEN:' '}]}),[400]);assert.equal(await prisma.doctor.count(),before);});
await test('Coaching acknowledgement requires an actual action',async()=>{const report=await prisma.coachingReport.findFirst({where:{repId:f.rep.id}});if(report)status(await api('rep','PATCH',`/coaching-reports/${report.id}`,{accept:false}),[400]);});
await test('Bulk pharmacy import validates all rows before saving',async()=>{const before=await prisma.pharmacy.count();status(await api('manager','POST','/pharmacies/bulk-import',{records:[{name:'QA valid',city:'Cairo',country:'Egypt',region:'QA Cairo',subRegion:'QA Nasr City'},{name:' '}]}),[400]);assert.equal(await prisma.pharmacy.count(),before);});
await test('Bulk pharmacy import saves selected records',async()=>{const r=await api('manager','POST','/pharmacies/bulk-import',{records:[{name:'QA API Imported Pharmacy',city:'Cairo',country:'Egypt',region:'QA Cairo',subRegion:'QA Nasr City'}]});status(r,[200]);assert.equal(r.data.imported,1);});
await test('Bulk doctor import saves selected records',async()=>{const r=await api('manager','POST','/doctors/bulk-import',{records:[{nameEN:'QA API Imported Doctor',avgPatientsPerDay:20}]});status(r,[201]);assert.equal(r.data.imported,1);});
await test('Bulk import rejects a batch above the supported limit',async()=>status(await api('manager','POST','/pharmacies/bulk-import',{records:Array.from({length:1001},()=>({name:'QA',city:'C',country:'E',region:'R',subRegion:'S'}))}),[400]));
await test('Manager assigned plan creates visits for the chosen representative',async()=>{const r=await api('manager','POST','/plans',{title:`QA Assigned Plan ${Date.now()}`,description:'QA assigned',type:'WEEKLY',repId:f.rep.id,startDate:'2026-10-05',endDate:'2026-10-11',objectives:['QA'],targetVisits:1,doctorsWithDates:[{doctorId:f.doctor.id,visitDate:'2026-10-06'}]});status(r,[201]);assert.equal(r.data.data.createdById,f.rep.id);status(await api('manager','PATCH',`/plans/${r.data.data.id}`,{status:'APPROVED'}),[200]);const visits=await prisma.visit.findMany({where:{planId:r.data.data.id}});assert.equal(visits.length,1);assert.equal(visits[0].userId,f.rep.id);});
await test('Plans cannot be assigned outside the team',async()=>status(await api('manager','POST','/plans',{repId:f.rep2.id}),[403]));
await test('Rep dashboard MTD excludes previous-month sales',async()=>{await prisma.sales.create({data:{sheetName:'QA historical metric',customer:'QA Pharmacy',order:`QA-old-${Date.now()}`,orderDate:new Date('2026-09-01'),qtyOrdered:1,untaxedTotal:999999,productId:f.product.id}});const expected=await prisma.sales.aggregate({where:{customer:'QA Pharmacy',orderDate:{gte:new Date('2026-10-01'),lt:new Date('2026-11-01')}},_sum:{untaxedTotal:true}});const r=await api('rep','GET','/dashboard/reps?date=2026-10-04');status(r,[200]);assert.equal(r.data.data.metrics.totalSales,expected._sum.untaxedTotal||0);});
let concurrentVisit;
await test('Concurrent report submission persists exactly once',async()=>{const visit=await prisma.visit.create({data:{doctorId:f.doctor.id,userId:f.rep.id,date:new Date('2026-10-05'),samples:[]}});concurrentVisit=visit.id;const body={visitId:visit.id,duration:'15 min',rating:'5',visitPurpose:'QA Concurrent',discussedTopics:['QA'],samplesProvided:[]};const rs=await Promise.all([api('rep','POST','/visits/visit-reports',body),api('rep','POST','/visits/visit-reports',body)]);assert.equal(rs.filter(r=>r.status===200).length,1);assert.equal(await prisma.visitReport.count({where:{visitId:visit.id}}),1);assert.equal((await prisma.visit.findUnique({where:{id:visit.id}})).status,'COMPLETED');});
await test('Completed visit cannot be silently rewritten',async()=>status(await api('rep','PATCH',`/visits/${concurrentVisit}`,{notes:'rewrite'}),[409]));
await test('Report rating validation preserves scheduled visit',async()=>{const visit=await prisma.visit.create({data:{doctorId:f.doctor.id,userId:f.rep.id,date:new Date('2026-10-06'),samples:[]}});status(await api('rep','POST','/visits/visit-reports',{visitId:visit.id,duration:'15 min',rating:'99',visitPurpose:'QA',discussedTopics:['QA']}),[400]);assert.equal((await prisma.visit.findUnique({where:{id:visit.id}})).status,'SCHEDULED');assert.equal(await prisma.visitReport.count({where:{visitId:visit.id}}),0);});
await test('Cancelled visit rejects report',async()=>{const visit=await prisma.visit.create({data:{doctorId:f.doctor.id,userId:f.rep.id,date:new Date('2026-10-06'),samples:[],status:'CANCELLED'}});status(await api('rep','POST','/visits/visit-reports',{visitId:visit.id,duration:'15 min',rating:'4',visitPurpose:'QA',discussedTopics:['QA']}),[400]);});
await test('Visit completion cannot bypass report',async()=>{const visit=await prisma.visit.create({data:{doctorId:f.doctor.id,userId:f.rep.id,date:new Date('2026-10-06'),samples:[]}});status(await api('rep','PATCH',`/visits/${visit.id}`,{status:'COMPLETED'}),[400]);});
await test('Supervisor report filters do not expose another team',async()=>{const visit=await prisma.visit.create({data:{doctorId:f.doctor.id,userId:f.rep2.id,date:new Date('2026-10-06'),samples:[]}});status(await api('rep2','POST','/visits/visit-reports',{visitId:visit.id,duration:'15 min',rating:'4',visitPurpose:'QA outside',discussedTopics:['QA']}),[200]);for(const suffix of ['', '&paginate=false']){const r=await api('supervisor','GET',`/visits/all-visit-reports?createdById=${f.rep2.id}${suffix}`);status(r,[200]);assert.ok(!r.data.data.some(x=>x.userId===f.rep2.id));}});
await test('Plan without doctors gives validation feedback',async()=>status(await api('rep','POST','/plans',{title:'QA Empty Plan',description:'QA',startDate:'2026-10-05',endDate:'2026-10-06',type:'WEEKLY',targetVisits:1,objectives:['QA']}),[400]));
await test('Reversed plan dates rejected',async()=>status(await api('rep','POST','/plans',{title:'QA Bad Plan',description:'QA',startDate:'2026-10-06',endDate:'2026-10-05',type:'WEEKLY',targetVisits:1,objectives:['QA'],doctorsWithDates:[]}),[400]));
await test('Appraisal uses the displayed 0–100 scale',async()=>status(await api('manager','POST','/appraisals',{repId:f.rep.id,period:'2026-10-01',salesPerformance:90,presentationSkills:95,sellingSkills:88}),[201]));
await test('Appraisal rejects scores above 100',async()=>status(await api('manager','POST','/appraisals',{repId:f.rep.id,period:'2026-10-01',presentationSkills:101}),[400]));
await test('String false is not an acknowledgement',async()=>{const a=await prisma.appraisal.findFirst({where:{repId:f.rep.id}});status(await api('rep','PATCH',`/appraisals/${a.id}`,{accept:'false'}),[400]);});
for(const [path,values,model] of [['regions',{name:'QA CRUD Region',country:'Egypt'},'region'],['sub-regions',{name:'QA CRUD Territory',regionId:f.region.id},'subRegion'],['accounts',{name:'QA CRUD Facility',subRegionId:f.subRegion.id},'accounts']]){
  let id;
  await test(`${path} create/edit/delete persists`,async()=>{let r=await api('manager','POST',`/${path}`,values);status(r,[201]);id=r.data.data.id;r=await api('manager','PATCH',`/${path}/${id}`,{name:'QA CRUD Edited'});status(r,[200]);assert.equal((await prisma[model].findUnique({where:{id}})).name,'QA CRUD Edited');status(await api('manager','DELETE',`/${path}/${id}`),[200]);assert.equal(await prisma[model].findUnique({where:{id}}),null);status(await api('manager','DELETE',`/${path}/${id}`),[404]);});
  await test(`Rep cannot manage ${path}`,async()=>status(await api('rep','POST',`/${path}`,values),[403]));
  await test(`${path} blank name rejected`,async()=>status(await api('manager','POST',`/${path}`,{...values,name:' '}),[400]));
}
for(const [path,id] of [['regions',f.region.id],['sub-regions',f.subRegion.id],['accounts',f.account.id]]) await test(`Referenced ${path} cannot be deleted`,async()=>status(await api('manager','DELETE',`/${path}/${id}`),[409]));
const sample={title:'QA File Sample',subject:'QA',description:'QA',urgency:'Medium',type:'SAMPLE',sampleData:[{productId:f.product.id,productName:'QA Medicine',amount:2}],doctorIds:[f.doctor.id]};
function requestForm(payload,files=[]){const fd=new FormData();for(const [key,value]of Object.entries(payload))fd.append(key,typeof value==='object'?JSON.stringify(value):String(value));for(const [name,content]of files)fd.append('pdfs',new Blob([content],{type:'application/pdf'}),name);return fd;}
await test('Canonical multipart sample data saves associations',async()=>{const r=await api('rep','POST','/requests',requestForm(sample));status(r,[201]);const v=await prisma.request.findUnique({where:{id:r.data.data.id},include:{doctors:true}});assert.equal(v.sampleData[0].amount,2);assert.equal(v.doctors[0].id,f.doctor.id);});
await test('Spoofed PDF rejected before upload',async()=>status(await api('rep','POST','/requests',requestForm({...sample,type:'EXPENSE',budget:100},[['spoof.pdf','not a pdf']])),[422]));
await test('Oversized attachment gets 413',async()=>status(await api('rep','POST','/requests',requestForm(sample,[['large.pdf',Buffer.alloc(5*1024*1024+1)]])),[413]));
const xlsx=require('xlsx');
const rows=[1,2].map(i=>({'Customer':'QA Pharmacy','Order':`QA-Order-${i}`,'Order Date':new Date('2026-10-04T12:00:00Z'),'Product Variant':'[QA001] QA Medicine','Qty Ordered':i,'Untaxed Total':100*i}));
function workbookBytes(records){const wb=xlsx.utils.book_new();xlsx.utils.book_append_sheet(wb,xlsx.utils.json_to_sheet(records),'QA');return xlsx.write(wb,{type:'buffer',bookType:'xlsx'});}
async function uploadSales(name,records,type='xlsx'){const fd=new FormData();fd.append('sheetName',name);const body=type==='csv'?xlsx.utils.sheet_to_csv(xlsx.utils.json_to_sheet(records)):workbookBytes(records);fd.append('sheet',new Blob([body],{type:type==='csv'?'text/csv':'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'}),`qa.${type}`);return api('manager','POST','/sales',fd);}
await test('Spreadsheet import keeps the final valid row',async()=>{const name=`QA-Sales-${Date.now()}`;const r=await uploadSales(name,rows);status(r,[201]);assert.equal(r.data.data.count,2);assert.equal(await prisma.sales.count({where:{sheetName:name}}),2);});
await test('Spreadsheet total row is excluded explicitly',async()=>{const r=await uploadSales(`QA-Totals-${Date.now()}`,[...rows,{'Customer':'Total','Qty Ordered':3,'Untaxed Total':300}]);status(r,[201]);assert.equal(r.data.data.count,2);});
await test('Unknown product import is atomic',async()=>{const name=`QA-Unknown-${Date.now()}`;status(await uploadSales(name,[rows[0],{...rows[1],'Product Variant':'[BAD] No such product'}]),[400]);assert.equal(await prisma.sales.count({where:{sheetName:name}}),0);});
await test('CSV advertised by UI can be imported',async()=>{const r=await uploadSales(`QA-CSV-${Date.now()}`,rows.map(r=>({...r,'Order Date':'2026-10-04'})),'csv');status(r,[201]);assert.equal(r.data.data.count,2);});
await test('Sales date filter and rep sales endpoint work',async()=>{status(await api('manager','GET','/sales?date=2026-10-04'),[200]);status(await api('rep','GET','/sales/reps'),[200]);});
await test('Product used in sales cannot be deleted',async()=>status(await api('manager','DELETE',`/products/${f.product.id}`),[409]));
await test('Pharmacy used in sales cannot be deleted',async()=>status(await api('manager','DELETE',`/pharmacies/${f.pharmacy.id}`),[409]));
// A valid, synthetic one-page PDF; no customer or employee data is transmitted.
function pdfBytes(){const objects=['<< /Type /Catalog /Pages 2 0 R >>','<< /Type /Pages /Kids [3 0 R] /Count 1 >>','<< /Type /Page /Parent 2 0 R /MediaBox [0 0 200 200] /Contents 4 0 R >>','<< /Length 0 >>\nstream\n\nendstream'];let s='%PDF-1.4\n',offsets=[0];for(let i=0;i<objects.length;i++){offsets.push(Buffer.byteLength(s));s+=`${i+1} 0 obj\n${objects[i]}\nendobj\n`;}const start=Buffer.byteLength(s);s+='xref\n0 5\n0000000000 65535 f \n'+offsets.slice(1).map(o=>String(o).padStart(10,'0')+' 00000 n \n').join('')+`trailer\n<< /Size 5 /Root 1 0 R >>\nstartxref\n${start}\n%%EOF`;return Buffer.from(s);}
await test('Real PDF request upload preserves every filename',async()=>{const r=await api('rep','POST','/requests',requestForm({...sample,title:'QA Real PDFs',type:'EXPENSE',budget:100},[['qa-invoice-1.pdf',pdfBytes()],['qa-invoice-2.pdf',pdfBytes()]]));status(r,[201]);assert.deepEqual(r.data.data.pdfs.map(p=>p.name),['qa-invoice-1.pdf','qa-invoice-2.pdf']);assert.ok(r.data.data.pdfs.every(p=>p.public_id&&p.url));});
await test('Expense total is derived from validated line items',async()=>{const r=await api('rep','POST','/requests',requestForm({...sample,title:'QA Personal Expense',type:'PERSONAL_EXPENSE',visitedCity:'Cairo',visitDaysCount:2,totalExpenseAmount:999,totalExpenseData:[{name:'Taxi',amount:50},{name:'Hotel',amount:100}]},[['qa-personal.pdf',pdfBytes()]]));status(r,[201]);assert.equal(r.data.data.totalExpenseAmount,150);});
await test('Valid leave PDF upload and approval persists',async()=>{const r=await api('rep','POST','/requests',requestForm({...sample,title:'QA Real Leave',type:'LEAVE',leaveType:'Annual',leaveStartDate:'2026-11-01',leaveEndDate:'2026-11-02'},[['qa-leave.pdf',pdfBytes()]]));status(r,[201]);assert.equal(r.data.data.leaveDaysCount,2);status(await api('manager','PATCH',`/requests/${r.data.data.id}`,{status:'APPROVED',response:'QA'}),[200]);});
const requests=await prisma.request.findMany({select:{pdfs:true}});
const assets=[...new Set(requests.flatMap(r=>r.pdfs.map(p=>p.public_id)).filter(Boolean))];
const {v2:cloudinary}=require('cloudinary');cloudinary.config({cloud_name:process.env.CLOUDINARY_CLOUD_NAME,api_key:process.env.CLOUDINARY_API_KEY,api_secret:process.env.CLOUDINARY_API_SECRET});
await test('Synthetic upload assets removed from Cloudinary',async()=>{for(const id of assets){const result=await cloudinary.uploader.destroy(id,{resource_type:'raw'});assert.ok(['ok','not found'].includes(result.result),`Cleanup failed for QA asset: ${result.result}`);}});
const summary={total:results.length,passed:results.filter(r=>r.pass).length,failed:results.filter(r=>!r.pass).length,removedSyntheticAssets:assets.length,results};
fs.writeFileSync(`${root}/audit/2026-10-04/full-system/extended-api.json`,JSON.stringify(summary,null,2));
console.log(JSON.stringify({...summary,results:results.filter(r=>!r.pass)},null,2));
await prisma.$disconnect();
