import { UserRole } from "@/lib/types";
import { FileText, CircleAlert, Star, TrendingUp } from "lucide-react";
import type { StatCardConfig } from "@/core/ui/stat-card-types";

export type CoachingStatConfig = StatCardConfig;

export const roleCoachingStatsMap: Record<UserRole, CoachingStatConfig[]> = {
  MANAGER: [
    {
      id: "total-reports",
      label: "Total Reports",
      helper: "All documented sessions",
      dataKey: "totalReports",
      icon: FileText,
      bgColor: "gradient-blue",
      tone: "navy",
    },
    {
      id: "awaiting-rep-feedback",
      label: "Awaiting Rep Feedback",
      helper: "Needs representative input",
      dataKey: "awaitingRepFeedback",
      icon: CircleAlert,
      bgColor: "gradient-orange",
      tone: "amber",
    },
    {
      id: "average-rating",
      label: "Average Rating",
      helper: "Across reported visits",
      dataKey: "averageRating",
      icon: Star,
      bgColor: "gradient-gold",
      tone: "gold",
    },
    {
      id: "this-month",
      label: "This Month",
      helper: "Reports created this month",
      dataKey: "thisMonth",
      icon: TrendingUp,
      bgColor: "gradient-green",
      tone: "navy",
    },
  ],
  SUPERVISOR: [
    {
      id: "total-reviews",
      label: "Total Reviews",
      helper: "All documented sessions",
      dataKey: "totalReviews",
      icon: FileText,
      bgColor: "gradient-blue",
      tone: "navy",
    },
    {
      id: "action-items",
      label: "Action Items",
      helper: "Follow-up items recorded",
      dataKey: "actionItems",
      icon: CircleAlert,
      bgColor: "gradient-orange",
      tone: "amber",
    },
    {
      id: "avg-performance",
      label: "Avg Performance",
      helper: "Across reviewed visits",
      dataKey: "avgPerformance",
      icon: Star,
      bgColor: "gradient-gold",
      tone: "gold",
    },
    {
      id: "this-month",
      label: "This Month",
      helper: "Reviews created this month",
      dataKey: "thisMonth",
      icon: TrendingUp,
      bgColor: "gradient-green",
      tone: "navy",
    },
  ],
  MEDICAL_REP: [
    {
      id: "total-reports",
      label: "Total Sessions",
      helper: "All coaching sessions",
      dataKey: "totalReports",
      icon: FileText,
      bgColor: "bg-[#E9F8F1] border border-[#CBEFDD] text-[#168557]",
      tone: "green",
    },
    {
      id: "pending-comments",
      label: "Pending Feedback",
      helper: "Waiting for your response",
      dataKey: "pendingComments",
      icon: CircleAlert,
      bgColor: "bg-[#FFF8E5] border border-[#E9DDB8] text-[#B18732]",
      tone: "amber",
    },
    {
      id: "average-rating",
      label: "Average Rating",
      helper: "Across your reported visits",
      dataKey: "averageRating",
      icon: Star,
      bgColor: "bg-[#F9FAFB] border border-[#E5E8EF] text-[#F59E0B]",
      tone: "gold",
    },
    {
      id: "this-month",
      label: "This Month",
      helper: "Sessions recorded this month",
      dataKey: "thisMonth",
      icon: TrendingUp,
      bgColor: "bg-[#E9F8F1] border border-[#CBEFDD] text-[#168557]",
      tone: "green",
    },
  ],
};
